const options = [
  {
    name: "Print Width",
    key: "printWidth",
    description: "Line length the printer will wrap on?",
    type: "input",
    validate: "integer",
  },
  {
    name: "Tab Width",
    key: "tabWidth",
    description: "Number of spaces per indentation-level?",
    type: "input",
    validate: "integer",
  },
  {
    name: "Tabs",
    key: "useTabs",
    description: "Indent lines with tabs? (vs spaces)",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Semicolons",
    key: "semi",
    description: "Print semicolons at end of every statement? (vs ASI only)",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Quotes",
    key: "singleQuote",
    description: "Use single quotes? (vs double)",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Quote Props",
    key: "quoteProps",
    description: "Change when properties in objects are quoted.",
    type: "buttons",
    options: ["as-needed", "consistent", "preserve"],
    validate: "string",
  },
  {
    name: "JSX Quotes",
    key: "jsxSingleQuote",
    description: "Use single quotes in JSX? (vs double)",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Trailing Commas",
    key: "trailingComma",
    description: "Print trailing commas when multi-line for?",
    type: "buttons",
    options: ["none", "es5", "all"],
    validate: "string",
  },
  {
    name: "Bracket Spacing",
    key: "bracketSpacing",
    description: "Print spaces between brackets in object literals?",
    type: "buttons",
    options: [true, false],
    examples: ["{ foo: bar }", "{foo: bar}"],
    validate: "boolean",
  },
  {
    name: "Bracket Line",
    key: "bracketSameLine",
    description: "Put > on the last line instead of a new line in JSX/HTML.",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Arrow Function Parentheses",
    key: "arrowParens",
    description: "Include parentheses around a sole arrow function parameter?",
    type: "buttons",
    options: ["avoid", "always"],
    examples: ["x => x", "(x) => x"],
    validate: "string",
  },
  {
    name: "Range Start",
    key: "rangeStart",
    description:
      "Format only a segment of a file, starting at what character offset? (inclusive)",
    type: "input",
    validate: "integer",
  },
  {
    name: "Range End",
    key: "rangeEnd",
    description:
      "Format only a segment of a file, ending at what character offset? (exclusive)",
    type: "input",
    validate: "integer",
  },
  {
    name: "Parser",
    key: "parser",
    description: "Specify which parser to use.",
    type: "input",
    validate: "string",
  },
  {
    name: "File Path",
    key: "filePath",
    description: "The input filepath (used to do parser inference).",
    type: "input",
    validate: "string",
  },
  {
    name: "Require Pragma",
    key: "requirePragma",
    description:
      "Format only files that contain a special comment (`@format` or `@prettier`).",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Insert Pragma",
    key: "insertPragma",
    description: "Insert `@format` pragma at the top of the file.",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Prose Wrap",
    key: "proseWrap",
    description: "Wrap markdown text?",
    type: "buttons",
    options: ["always", "never", "preserve"],
    validate: "string",
  },
  {
    name: "HTML Whitespace Sensitivity",
    key: "htmlWhitespaceSensitivity",
    description: "How to handle whitespaces in HTML.",
    type: "buttons",
    options: ["css", "strict", "ignore"],
    validate: "string",
  },
  {
    name: "Vue Indent Script and Style",
    key: "vueIndentScriptAndStyle",
    description: "Indent `<script>` and `<style>` tags in Vue files.",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "End of Line",
    key: "endOfLine",
    description: "Which end of line characters to apply.",
    type: "buttons",
    options: ["lf", "crlf", "cr", "auto"],
    validate: "string",
  },
  {
    name: "Embedded Language Formatting",
    key: "embeddedLanguageFormatting",
    description:
      "Control whether Prettier formats quoted code embedded in the file.",
    type: "buttons",
    options: ["auto", "off"],
    validate: "string",
  },
  {
    name: "Single Attribute Per Line",
    key: "singleAttributePerLine",
    description: "Enforce each attribute on its own line in HTML/JSX/Vue.",
    type: "buttons",
    options: [true, false],
    validate: "boolean",
  },
  {
    name: "Official Plugins",
    key: "plugins",
    description: "Select official Prettier plugins to use.",
    type: "multiselect",
    options: [
      "@prettier/plugin-php",
      "@prettier/plugin-pug",
      "@prettier/plugin-ruby",
      "@prettier/plugin-xml",
    ],
    validate: "string[]",
  },
];

export default options;
